### ISSUE TITLE
Theme customization doesn't work

### ISSUE THREAD

**Issue by goottime** [forus-labs/forui#130]
**Describe the bug**
I tried to change the crown parameters using methods as in the [documentation via copyWith](https://forui.dev/docs/themes#customize-themes). The problem is that the values ​​in the FThemeData object change, but they don't work in the application itself.

**To Reproduce**
1. Create a flutter project
2. Add the following code

**Expected behavior**
The colors should change, the borderRadius should become 0, the font should change.

**Screenshots**
In my implementation nothing was applied, the color remained the same, the corners remained rounded.

![image](https://github.com/user-attachments/assets/1d0c00b2-1069-4bd7-b7d5-ad7a5941442c)

**Device:**
 - Flutter version: 3.22.2 
 - Forui version: 0.3.0
 - Device: Emulator Pixel 8
 - OS: Android 15 (API 35)

**Additional context**

main.dart
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _router = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'MyApp',
      routerConfig: _router.config(),
      builder: (context, child) => FTheme(
        data: FThemes.zinc.dark.copyWith(
          colorScheme: FThemes.zinc.dark.colorScheme.copyWith(
            primary: const Color(0xFFFF2222),
            primaryForeground: const Color(0xFFFFFFFF),
          ),
          typography: FThemes.zinc.dark.typography.copyWith(
            defaultFontFamily: 'GolosText',
          ),
          style: FThemes.zinc.dark.style.copyWith(
            borderRadius: BorderRadius.zero,
          ),
        ),
        child: child!,
      ),
    );
  }
}
```

button implementation
```
class AccountPage extends StatelessWidget {
  const AccountPage({super.key});

  @override
  Widget build(BuildContext context) {
    return FScaffold(
        content: Center(
            child: FButton(
              label: const Text('Button'),
              onPress: () {},
            )
        )
    );
  }
}
```

**Comment by Pante** [comment]
Thanks for bringing this to our attention. The problem is that widget-specific styles aren't being re-created after the global styles are updated. It's quite a serious issue and we'll probably release an update soon to address this.

As a workaround:
```dart
class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _router = AppRouter();

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'MyApp',
      routerConfig: _router.config(),
      builder: (context, child) {
        // Override global styles here
        var theme = FThemeData.inherit(
          colorScheme: FThemes.zinc.dark.colorScheme.copyWith(
            primary: const Color(0xFFFF2222),
            primaryForeground: const Color(0xFFFFFFFF),
          ),
          typography: FThemes.zinc.dark.typography.copyWith(
            defaultFontFamily: 'GolosText',
          ),
          style: FThemes.zinc.dark.style.copyWith(
            borderRadius: BorderRadius.zero,
          ),
        );
        
        // Override widget specific styles using copyWith(...) method here
        theme = theme.copyWith(alertStyles: theme.alertStyles);

        return FTheme(
          data: theme,
          child: child!,
        );
      },
    );
  }
}
```

**Comment by Pante** [comment]
I'm going to re-open it as it should be something that we address regardless.

**Comment by DucThu-Dev** [comment]
Hi, I use the same implementation, but font do not applied.
I add fonts at 'assets/fonts/' and registered it in pubspec.yaml.
Could you help to check Mr. @Pante .

**Comment by DucThu-Dev** [comment]
Currently, I workarounds like this
`              final themeData = FThemeData.inherit(
                colorScheme: FThemes.zinc.light.colorScheme,
                typography: FThemes.zinc.light.typography.copyWith(
                  defaultFontFamily: 'Lexend',
                  base: FThemes.zinc.light.typography.base.copyWith(fontFamily: 'Lexend'),
                  xs: FThemes.zinc.light.typography.xs.copyWith(fontFamily: 'Lexend'),
                  sm: FThemes.zinc.light.typography.sm.copyWith(fontFamily: 'Lexend'),
                  lg: FThemes.zinc.light.typography.lg.copyWith(fontFamily: 'Lexend'),
                  xl: FThemes.zinc.light.typography.xl.copyWith(fontFamily: 'Lexend'),
                  xl2: FThemes.zinc.light.typography.xl2.copyWith(fontFamily: 'Lexend'),
                  xl3: FThemes.zinc.light.typography.xl3.copyWith(fontFamily: 'Lexend'),
                  xl4: FThemes.zinc.light.typography.xl4.copyWith(fontFamily: 'Lexend'),
                  xl5: FThemes.zinc.light.typography.xl5.copyWith(fontFamily: 'Lexend'),
                  xl6: FThemes.zinc.light.typography.xl6.copyWith(fontFamily: 'Lexend'),
                  xl7: FThemes.zinc.light.typography.xl7.copyWith(fontFamily: 'Lexend'),
                  xl8: FThemes.zinc.light.typography.xl8.copyWith(fontFamily: 'Lexend'),
                ),
                style: FThemes.zinc.light.style,
              );`
