### ISSUE TITLE
Feedback for “Alert”

### ISSUE THREAD

**Issue by tameryalcin** [forus-labs/forui#150]
flutter_bootstrap.js:1 Refused to execute script from 'https://demo.forui.dev/alert/main.dart.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

widget preview

**Comment by Pante** [comment]
Seems like it's caused by https://github.com/flutter/flutter/issues/152995. We'll pin the docs deployment build to Flutter 3.22.
