### ISSUE TITLE
How can we use materialapp and the forui theme both?

### ISSUE THREAD

**Issue by creeponsky** [forus-labs/forui#269]
Title: How to Use MaterialApp and ForUI Theme Together for Consistent Theming?

Is your feature request related to a problem? Please describe.
When using Material components (such as Scaffold) alongside ForUI, I notice that the theme settings don't sync properly with ForUI’s theme. Although I could try setting ThemeData, I’d wanna try to use ForUI entirely. However, some UI elements—such as Material's InkWell, which I couldn’t replicate with ForUI’s FButton or other components—seem essential. When I try using these Material components, like InkWell, I end up needing to use Scaffold, which brings theme inconsistencies. Ideally, I want all Material components to look and behave consistently with ForUI's theme.

Describe the solution you'd like
I’m looking for one of the following solutions:

A way to completely replace Material components, so that I can rely solely on ForUI without needing Material elements.
A way to synchronize the Material theme with ForUI’s theme, so the visual style remains consistent without requiring additional styling adjustments.
Describe alternatives you've considered
I've tried replicating Material components like InkWell with FButton and other ForUI components, but haven’t succeeded in achieving the same functionality and look.

Additional context
Here's a screenshot of the UI I'm trying to achieve. My goal is a button-like appearance, but I’m still new to Flutter and haven’t been able to accomplish this with ForUI’s FButton alone. :(
![image](https://github.com/user-attachments/assets/a82137f7-be59-49ac-bf40-74202ddac57f)
So, I need to use Material’s Scaffold, which is where the theme inconsistency arises.

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  WakelockPlus.enable();

  runApp(const ProviderScope(child: Application()));
}

class Application extends StatefulWidget {
  const Application({super.key});

  @override
  State<Application> createState() => _ApplicationState();
}

class _ApplicationState extends State<Application> {
  @override
  Widget build(BuildContext context) => FTheme(
        data: FThemes.zinc.dark,
        child: FScaffold(
          content: Scaffold(
            body: InkWell(
              onTap: () {},
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                child: Row(
                  children: [
                    Text(
                      "test",
                      style: const TextStyle(
                        fontSize: 16,
                        color: Color.fromARGB(255, 230, 70, 70),
                      ),
                    ),
                    const Spacer(),
                    const Icon(
                      Icons.chevron_right,
                      color: Colors.white54,
                    ),
                  ],
                ),
              ),
            ),
          ),
          footer: FBottomNavigationBar(
            index: 0,
            children: [
              FBottomNavigationBarItem(
                icon: FIcon(FAssets.icons.house),
                label: const Text('test'),
              ),
            ],
          ),
        ),
      );
}
```

**Comment by Pante** [comment]
Thanks for the filing the issue. Unfortunately we don't automatically map Forui's theme to Material's theme or vice versa. 

> A way to completely replace Material components, so that I can rely solely on ForUI without needing Material elements.

Could you list some of the widgets that are missing? It'll help greatly with our planning!

For the particular UI you attached, it seems really similar to a `FTileGroup`, https://dev.forui.dev/docs/tile/tile-group, which we are planning to release either this week or early next week. Also, it's perfectly fine to use `Scaffold` instead of `FScaffold`, Forui widgets will still work!
