### ISSUE TITLE
Broken links in API Documentation

### ISSUE THREAD

**Issue by de1mat** [forus-labs/forui#307]
**Describe the bug**
The [API Reference documentation](https://pub.dev/documentation/forui/latest/) is linked to from the Forui docs in multiple places, including from each Widget page.

But the docs are broken, showing 404 for all widgets.

**To Reproduce**
1. Go to https://pub.dev/documentation/forui/latest/
2. Click on any Widget in the left menu
4. See 404 error

**Expected behavior**
Show the API docs for the widget.

**Comment by Pante** [comment]
Strange, I generated a local copy of the docs in which all the links are working.

**Comment by Pante** [comment]
I opened a bug report for this on pub dev's side, https://github.com/dart-lang/pub-dev/issues/8398.

**Comment by Pante** [comment]
Issue should be resolved now!
