### ISSUE TITLE
White border when navigating

### ISSUE THREAD

**Issue by Fischer96** [forus-labs/forui#327]
**Describe the bug**
When navigating using AutoRoute i have a weird white/transparent border. My main page has the usual setup with a FScaffold. The child page also has a FScaffold with a FHeader.nested. How can i fix this?

**To Reproduce**
1. Create two pages each having a FScaffold
2. Navigate from one page to another

**Expected behavior**
A way to set the color or avoid this border

**Screenshots**
![chrome_fYfNeO0NXJ](https://github.com/user-attachments/assets/9c002a4d-c6a9-4ef6-ad4d-7c2ffa3f90a0)

**Device (please complete the following information):**
 - Flutter version: 3.27.0
 - Forui version: 0.8.0
 - Device: All
 - OS: All
 - Browser: All
 - Version: All

**Additional context**

**Comment by Pante** [comment]
Thanks for filing the issue. Does it affect both Android & iOS? Also, are you using `MaterialApp` or `CupertinoApp`? Asking because `FScaffold` doesn't touch any page transitions/animations.

**Comment by Fischer96** [comment]
Both platforms and i use MaterialApp.router 👍🏼

**Comment by Pante** [comment]
I was able to replicate the issue using the following code:

<details>

<summary>MRE</summary>

```dart
void main() {
  runApp(App());
}

class App extends StatelessWidget {
  final _router = _AppRouter();

  App({super.key});

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routerConfig: _router.config(),
        builder: (context, child) => FTheme(
          data: FThemes.zinc.dark,
          child: child!,
        ),
      );
}

@RoutePage()
class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) => FScaffold(
        header: FHeader(
          title: const Text('Example'),
          actions: [
            FHeaderAction(
              icon: FIcon(FAssets.icons.plus),
              onPress: () => context.router.push(const NestedRoute()),
            ),
          ],
        ),
        content: const Placeholder(),
      );
}

@RoutePage()
class NestedPage extends StatelessWidget {
  const NestedPage({super.key});

  @override
  Widget build(BuildContext context) => FScaffold(
        header: FHeader.nested(
          title: const Text('Nested'),
          prefixActions: [
            FHeaderAction(
              icon: FIcon(FAssets.icons.arrowLeft),
              onPress: () => context.router.popForced(),
            ),
          ],
        ),
        content: const Placeholder(),
      );
}

@AutoRouterConfig()
class _AppRouter extends RootStackRouter {
  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: HomeRoute.page, initial: true),
        AutoRoute(path: '/nested', page: NestedRoute.page),
      ];
}
```

</details>

Digging further into the issue, it seems to be caused by Material's default page transition theme for Android, `ZoomPageTransitionsBuilder` using the theme's background color, which is this case is white/really light shade of purple.

To fix this, `ZoomPageTransitionsBuilder` needs to be overridden with a different color. In this case, `Colors.transparent` works fine.

```dart
@override
Widget build(BuildContext context) => MaterialApp.router(
      routerConfig: _router.config(),
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.white),
        useMaterial3: true,
        pageTransitionsTheme: PageTransitionsTheme( // override the default android page transition builder
          builders: {
            ...const PageTransitionsTheme().builders,
            TargetPlatform.android: const ZoomPageTransitionsBuilder(
              backgroundColor: Colors.transparent,
            ),
          },
        ),
      ),
      builder: (context, child) => FTheme(
        data: FThemes.zinc.dark,
        child: child!,
      ),
    );
```

It's technically not an issue with Forui, but we should consider documenting it, perhaps in the getting started page? What do you think? @kawaijoe
