### ISSUE TITLE
Documentation examples not valid?

### ISSUE THREAD

**Issue by p4-k4** [forus-labs/forui#329]
As per screenshot, a bunch of undefined stuff taking code straight from [documentation example:](https://forui.dev/docs/tile/select-menu-tile)
![Screenshot 2024-12-29 at 9 23 49 PM](https://github.com/user-attachments/assets/25494f03-2833-4895-8f38-45c1d81273cb)

`forui: ^0.7.0`
```sh
Flutter 3.27.0-0.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fc011960a2 (6 weeks ago) • 2024-11-14 12:19:18 -0800
Engine • revision 397deba30f
Tools • Dart 3.6.0 (build 3.6.0-334.4.beta) • DevTools 2.40.1
```

Haven't tried any other examples, package looked promising but gave up on it after running into a few issues.

**Comment by Pante** [comment]
Thanks for taking the time to file the issue! 

It seems like we forgot to update the documentation for some of the parameters. On another note, the scroll-related parameters were introduced in 0.8.0. Please do consider upgrading!
